@startuml
class MinesweeperGameComponent {
 + game: MinesweeperGame
 + tabledField: MinesweeperField[]
 + reset()
}
class MinesweeperGame {
    - width: number
    - height: number
    - bombs: number
    + revealedCounter: number
    + fields: MinesweeperField[]
    - initNeighbours()
    - getField()
    + reset()
}

MinesweeperGameComponent --> MinesweeperGame


@enduml