@startuml
class MinesweeperGameComponent {
    + game: MinesweeperGame
    + tabledField: MinesweeperField[]
    + reset()
}
class MinesweeperGame {
    - width: number
    - height: number
    - bombs: number
    + revealedCounter: number
    + fields: MinesweeperField[]
    - initNeighbours()
    - getField()
    + reset()
}

class MinesweeperField  {
    
}

class MinesweeperFieldComponent {
    + field
    + state
    + $onChanges()
}

MinesweeperGameComponent --> MinesweeperGame
MinesweeperGameComponent --> MinesweeperField
MinesweeperGame --> MinesweeperField
MinesweeperFieldComponent --> MinesweeperField


@enduml